// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcS_zXK4WbfMS84Hn1xNOD43pNQ9yZuao',
    appId: '1:57101567076:web:6ca4579964bb3304314b71',
    messagingSenderId: '57101567076',
    projectId: 'oversized-recyclable-items',
    authDomain: 'oversized-recyclable-items.firebaseapp.com',
    storageBucket: 'oversized-recyclable-items.firebasestorage.app',
    measurementId: 'G-46TK6SN7YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAniwGEs9cyDXNT9iG3L76fkn_NLZYCXeM',
    appId: '1:57101567076:android:6c7be7841538813b314b71',
    messagingSenderId: '57101567076',
    projectId: 'oversized-recyclable-items',
    storageBucket: 'oversized-recyclable-items.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq1uPL7hbVinGBQ-B560uRXfYGBiogNbM',
    appId: '1:57101567076:ios:8b6b5342110bb8af314b71',
    messagingSenderId: '57101567076',
    projectId: 'oversized-recyclable-items',
    storageBucket: 'oversized-recyclable-items.firebasestorage.app',
    iosBundleId: 'com.example.oversizedRecyclableItemsEcosystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq1uPL7hbVinGBQ-B560uRXfYGBiogNbM',
    appId: '1:57101567076:ios:8b6b5342110bb8af314b71',
    messagingSenderId: '57101567076',
    projectId: 'oversized-recyclable-items',
    storageBucket: 'oversized-recyclable-items.firebasestorage.app',
    iosBundleId: 'com.example.oversizedRecyclableItemsEcosystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcS_zXK4WbfMS84Hn1xNOD43pNQ9yZuao',
    appId: '1:57101567076:web:be5755a14b5ff7c1314b71',
    messagingSenderId: '57101567076',
    projectId: 'oversized-recyclable-items',
    authDomain: 'oversized-recyclable-items.firebaseapp.com',
    storageBucket: 'oversized-recyclable-items.firebasestorage.app',
    measurementId: 'G-Q6Q9PML17T',
  );
}
